token : "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11" # your token

db : # example for docker compose
  host : "db"
  port : 5432
  username : "app"
  password : "12345"
  name : "manager"

hash_salt: "you salt for hashing"
argon_salt: "yor salt for argon"